// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'info': string;
  'infoIcon': string;
  'rightSideContainer': string;
  'spacebar': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
