// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'grey': string;
  'size14': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
