// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'homeContainer': string;
  'iconContainer': string;
  'image': string;
  'imagesContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
